title: 'J. Yoon'
description: 'Academic website for research interests, projects, notes, and application materials'
url: 'https://j-y00n.github.io'
baseurl: ''
lang: 'en'
timezone: 'Asia/Seoul'
markdown: kramdown
permalink: pretty

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:title/
  publications:
    output: true
    permalink: /publications/:name/
  projects:
    output: true
    permalink: /projects/:name/
  notes:
    output: true
    permalink: /notes/:name/

defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: publications
    values:
      section: publications
  - scope:
      path: ''
      type: projects
    values:
      section: projects
  - scope:
      path: ''
      type: notes
    values:
      section: notes
